"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { parcelSchema, type ParcelFormData } from "@/lib/validations";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { toast } from "sonner";
import {
  ArrowLeft,
  ArrowRight,
  Loader2,
  User,
  MapPin,
  Package,
  CheckCircle2,
} from "lucide-react";

// ============================================================
// Parcel Creation — multi-step form.
// Step 1: Sender details
// Step 2: Recipient details
// Step 3: Parcel specs + assign driver/vehicle
// Step 4: Review & submit
// ============================================================

export default function NewParcelPage() {
  const [step, setStep] = useState(1);
  const [isLoading, setIsLoading] = useState(false);

  const {
    register,
    handleSubmit,
    watch,
    trigger,
    formState: { errors },
  } = useForm<ParcelFormData>({
    resolver: zodResolver(parcelSchema),
  });

  async function handleNext(nextStep: number) {
    const fields: (keyof ParcelFormData)[][] = [
      ["sender_name", "sender_address"],
      ["recipient_name", "recipient_address", "recipient_phone"],
      ["weight_kg", "notes"],
    ];

    const stepFields = fields[step - 1];
    const isValid = await trigger(stepFields);
    if (isValid) setStep(nextStep);
  }

  async function onSubmit(data: ParcelFormData) {
    setIsLoading(true);
    // In production: write to Supabase, tracking code auto-generated by trigger
    console.log("Parcel created:", data);
    toast.success("Parcel created! Tracking code will be generated automatically.");
    setIsLoading(false);
    setStep(4);
  }

  const formValues = watch();

  const steps = [
    { num: 1, label: "Sender", icon: User },
    { num: 2, label: "Recipient", icon: MapPin },
    { num: 3, label: "Parcel", icon: Package },
    { num: 4, label: "Done", icon: CheckCircle2 },
  ];

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">New Parcel</h1>
        <p className="text-muted-foreground">
          Register a new parcel for delivery.
        </p>
      </div>

      {/* Step indicator */}
      <div className="flex items-center justify-center gap-2">
        {steps.map((s, i) => (
          <div key={s.num} className="flex items-center gap-2">
            <div
              className={`flex items-center justify-center w-8 h-8 rounded-full text-sm font-medium transition-all ${
                step >= s.num
                  ? "bg-primary text-primary-foreground"
                  : "bg-muted text-muted-foreground"
              }`}
            >
              {step > s.num ? <CheckCircle2 className="h-4 w-4" /> : s.num}
            </div>
            {i < steps.length - 1 && (
              <div
                className={`w-8 sm:w-12 h-0.5 transition-all ${
                  step > s.num ? "bg-primary" : "bg-muted"
                }`}
              />
            )}
          </div>
        ))}
      </div>

      <form onSubmit={handleSubmit(onSubmit)}>
        {/* STEP 1: Sender */}
        {step === 1 && (
          <Card className="border-border/50">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <User className="h-5 w-5 text-primary" />
                Sender Information
              </CardTitle>
              <CardDescription>Who is sending this parcel?</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="sender_name">Sender Name</Label>
                <Input
                  id="sender_name"
                  placeholder="Jumia Kenya"
                  {...register("sender_name")}
                />
                {errors.sender_name && (
                  <p className="text-sm text-destructive">
                    {errors.sender_name.message}
                  </p>
                )}
              </div>
              <div className="space-y-2">
                <Label htmlFor="sender_address">Sender Address</Label>
                <Input
                  id="sender_address"
                  placeholder="Mombasa Rd, Nairobi"
                  {...register("sender_address")}
                />
                {errors.sender_address && (
                  <p className="text-sm text-destructive">
                    {errors.sender_address.message}
                  </p>
                )}
              </div>
            </CardContent>
            <CardFooter className="justify-end">
              <Button type="button" onClick={() => handleNext(2)}>
                Next <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </CardFooter>
          </Card>
        )}

        {/* STEP 2: Recipient */}
        {step === 2 && (
          <Card className="border-border/50">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <MapPin className="h-5 w-5 text-primary" />
                Recipient Information
              </CardTitle>
              <CardDescription>Where is this parcel going?</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="recipient_name">Recipient Name</Label>
                <Input
                  id="recipient_name"
                  placeholder="Peter Kamau"
                  {...register("recipient_name")}
                />
                {errors.recipient_name && (
                  <p className="text-sm text-destructive">
                    {errors.recipient_name.message}
                  </p>
                )}
              </div>
              <div className="space-y-2">
                <Label htmlFor="recipient_address">Recipient Address</Label>
                <Input
                  id="recipient_address"
                  placeholder="Kilimani, Nairobi"
                  {...register("recipient_address")}
                />
                {errors.recipient_address && (
                  <p className="text-sm text-destructive">
                    {errors.recipient_address.message}
                  </p>
                )}
              </div>
              <div className="space-y-2">
                <Label htmlFor="recipient_phone">Recipient Phone</Label>
                <Input
                  id="recipient_phone"
                  placeholder="+254700000000"
                  {...register("recipient_phone")}
                />
                {errors.recipient_phone && (
                  <p className="text-sm text-destructive">
                    {errors.recipient_phone.message}
                  </p>
                )}
              </div>
            </CardContent>
            <CardFooter className="justify-between">
              <Button
                type="button"
                variant="outline"
                onClick={() => setStep(1)}
              >
                <ArrowLeft className="mr-2 h-4 w-4" /> Back
              </Button>
              <Button type="button" onClick={() => handleNext(3)}>
                Next <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </CardFooter>
          </Card>
        )}

        {/* STEP 3: Parcel Details */}
        {step === 3 && (
          <Card className="border-border/50">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Package className="h-5 w-5 text-primary" />
                Parcel Details
              </CardTitle>
              <CardDescription>
                Specify the parcel weight and any notes.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="weight_kg">Weight (kg)</Label>
                <Input
                  id="weight_kg"
                  type="number"
                  step="0.1"
                  placeholder="2.5"
                  className="font-code"
                  {...register("weight_kg", { valueAsNumber: true })}
                />
                {errors.weight_kg && (
                  <p className="text-sm text-destructive">
                    {errors.weight_kg.message}
                  </p>
                )}
              </div>
              <div className="space-y-2">
                <Label htmlFor="notes">Notes (optional)</Label>
                <Textarea
                  id="notes"
                  placeholder="Fragile, handle with care..."
                  {...register("notes")}
                />
              </div>
            </CardContent>
            <CardFooter className="justify-between">
              <Button
                type="button"
                variant="outline"
                onClick={() => setStep(2)}
              >
                <ArrowLeft className="mr-2 h-4 w-4" /> Back
              </Button>
              <Button type="submit" disabled={isLoading}>
                {isLoading ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Package className="mr-2 h-4 w-4" />
                )}
                Create Parcel
              </Button>
            </CardFooter>
          </Card>
        )}

        {/* STEP 4: Confirmation */}
        {step === 4 && (
          <Card className="border-border/50 text-center">
            <CardHeader className="space-y-4">
              <div className="flex justify-center">
                <div className="w-16 h-16 rounded-full bg-success/20 flex items-center justify-center">
                  <CheckCircle2 className="h-8 w-8 text-success" />
                </div>
              </div>
              <CardTitle>Parcel Created!</CardTitle>
              <CardDescription>
                Tracking code has been auto-generated. The parcel is now in
                &ldquo;Received&rdquo; status and ready for assignment.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="rounded-lg border bg-muted/50 p-4 space-y-2">
                <p className="text-sm text-muted-foreground">Summary</p>
                <p className="text-sm">
                  <strong>From:</strong> {formValues.sender_name}
                </p>
                <p className="text-sm">
                  <strong>To:</strong> {formValues.recipient_name},{" "}
                  {formValues.recipient_address}
                </p>
                <p className="text-sm">
                  <strong>Weight:</strong> {formValues.weight_kg} kg
                </p>
              </div>
            </CardContent>
            <CardFooter className="justify-center gap-3">
              <Button variant="outline" onClick={() => { setStep(1); }}>
                Create Another
              </Button>
              <Button onClick={() => window.location.href = "/dispatch"}>
                Back to Dashboard
              </Button>
            </CardFooter>
          </Card>
        )}
      </form>
    </div>
  );
}
